[project]
name = "pydantic-csv"
version = "0.1.1"
description = "Convert CSV to pydantic.BaseModel and vice versa"
authors = [{ name = "Nathan Richard", email = "contact@nathanrichard.dev" }]
requires-python = ">=3.9,<4"
readme = "README.md"
license-files = ["LICENSE", "AUTHORS.md"]
dependencies = [
    "pydantic>=2.7.4,<3",
]
[dependency-groups]
dev = [
    "pytest>=8.2.2,<9",
    "pre-commit>=3.7.1,<4",
]

[build-system]
requires = ["uv_build>=0.9.10,<0.10.0"]
build-backend = "uv_build"